global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: nodejs-red-example
    static_configs:
      - targets:
        - docker.for.mac.host.internal:8000
  # - job_name: prometheus
  #   static_configs:
  #     - targets:
  #       - localhost:9090
  # - job_name: grafana
  #   static_configs:
  #     - targets:
  #       - gra:3000