{
 "title": "nodejs red metric example",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Rate (R): Number of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{name=\"nodejs-red-example\"}[5m])) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Errors (E): The number of failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{name=\"nodejs-red-example\",status_code=~\"5.*\"}[5m])) by (path)",
     "legendFormat": "{{path}} 5xx response"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{name=\"nodejs-red-example\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Duration (D): The amount of time to process a request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\"}[5m])) by (le, path, method))",
     "legendFormat": "p90 {{method}} {{path}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, path, method))",
     "legendFormat": "p50 {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Rate (R): Number of requests per minute by Couter metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{name=\"nodejs-red-example\"}[5m])) by (path, method)",
     "legendFormat": "{{path}} {{method}}"
    }
   ]
  },
  {
   "title": "Awesome Node Reqeust Duration Summary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Awesome Node Reqeust Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(sum by (le) (increase(http_request_duration_seconds_bucket{name=\"nodejs-red-example\"}[5m])), \"le\", \"Inf\", \"le\", \"\\\\+Inf\")",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "Percentage of requests shorter than 0.3 seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "(sum by (name) (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"0.3\"}[5m])) / sum by (name) (rate(http_request_duration_seconds_count{name=\"nodejs-red-example\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Percentage of requests shorter than 0.3 seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum by (name) (increase(http_request_duration_seconds_bucket{name=\"nodejs-red-example\", le=\"0.3\"}[1d])) / sum by (name) (increase(http_request_duration_seconds_count{name=\"nodejs-red-example\"}[1d]))) * 100"
    }
   ]
  },
  {
   "title": "Awesome Node Request Duration (Unstacked Buckets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"0.03\"}[5m])) - sum (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"0.003\"}[5m]))",
     "legendFormat": "0.003  <  t  <  0.03"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"0.1\"}[5m])) - sum (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"0.03\"}[5m]))",
     "legendFormat": "0.03  <  t  <  0.1"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"0.3\"}[5m])) - sum (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"0.1\"}[5m]))",
     "legendFormat": "0.1  <  t  < 0.3"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"1.5\"}[5m])) - sum (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"0.3\"}[5m]))",
     "legendFormat": "0.3  <  t  <  1.5"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"10\"}[5m])) - sum (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"1.5\"}[5m]))",
     "legendFormat": "1.5  <  t  <  10"
    },
    {
     "expr": "sum (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"+Inf\"}[5m])) - sum (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\",le=\"10\"}[5m]))",
     "legendFormat": "10  <  t"
    }
   ]
  },
  {
   "title": "Awesome Node Request Duration (Stacked All Buckets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_seconds_bucket{name=\"nodejs-red-example\"}[5m]))\n",
     "legendFormat": "Requests > {{le}}s per second"
    }
   ]
  }
 ]
}